import { useState } from 'react';
import './PaintSessionSetupModal.css';
type Candidate = { userId: number; name: string };
type Created = { sessionId: string; matrixRoomId: string; channelId: number };
type Matrix = { getMediaConfig(): Promise<Record<string, number>>; joinRoom(roomId: string): Promise<unknown>; uploadContent(file: File, opts?: unknown): Promise<{ content_uri: string }>; sendMessage(roomId: string, content: Record<string, unknown>): Promise<{ event_id: string }>; };
export function PaintSessionSetupModal({ channelId, channelRoomId, candidates, paintApi, matrixClient, onAttachSource, onComplete, onClose }: { channelId: number; channelRoomId: string; candidates: Candidate[]; paintApi: { createSession(input: { channelId: number; participantUserIds: number[] }): Promise<Created> }; matrixClient: Matrix; onAttachSource(sessionId: string, sourceEventId: string): Promise<unknown>; onComplete?: (sessionId: string) => void; onClose?: () => void }) {
  const [selected, setSelected] = useState<number[]>([]); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const start = async () => { if (!file) { setError('Choose a source image.'); return; } setSaving(true); setError(null); try { const created = await paintApi.createSession({ channelId, participantUserIds: selected }); const config = await matrixClient.getMediaConfig(); const limit = config['m.upload.size']; if (limit && file.size > limit) throw new Error('The source image exceeds the Matrix upload limit.'); await matrixClient.joinRoom(created.matrixRoomId); const uploaded = await matrixClient.uploadContent(file, { type: file.type, name: file.name }); const source = await matrixClient.sendMessage(created.matrixRoomId, { msgtype: 'm.image', body: file.name, url: uploaded.content_uri, info: { mimetype: file.type, size: file.size } }); await onAttachSource(created.sessionId, source.event_id); await matrixClient.sendMessage(channelRoomId, { msgtype: 'm.text', body: 'Collaborative paint session', 'com.brmble.paint': { sessionId: created.sessionId, hostUserId: 0, participantUserIds: selected, channelId: created.channelId, status: 'active', sourceEventId: source.event_id } }); onComplete?.(created.sessionId); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to start paint. Please try again.'); } finally { setSaving(false); } };
  return <div className="paint-setup-backdrop" role="dialog" aria-modal="true" aria-label="Start collaborative paint"><div className="paint-setup-modal"><h2>Start collaborative paint</h2>{candidates.map(candidate => <label key={candidate.userId}><input aria-label={candidate.name} type="checkbox" checked={selected.includes(candidate.userId)} onChange={() => setSelected(value => value.includes(candidate.userId) ? value.filter(id => id !== candidate.userId) : [...value, candidate.userId])} />{candidate.name}</label>)}<label>Source image<input aria-label="Source image" type="file" accept="image/*" onChange={event => setFile(event.target.files?.[0] ?? null)} /></label>{error && <p role="alert">{error}</p>}<div><button onClick={onClose}>Cancel</button><button onClick={() => void start()} disabled={saving}>{saving ? 'Starting...' : 'Start paint'}</button></div></div></div>;
}
