import { useEffect, useRef, useState } from 'react';
import type { PaintPreview, PaintSessionSnapshot, PaintStrokeInput, PaintTool } from '../../types/paint';
import { applyPaintStrokeToContext, composePaintPng, initializePaintCanvases, loadPaintSourceImage, normalizeCanvasPoint, type MatrixMediaClient } from '../../utils/paintCanvas';
import { PaintToolbar } from './PaintToolbar';
import './PaintEditor.css';
type Api = { commitStroke(id: string, stroke: PaintStrokeInput): Promise<unknown> | void; sendPreview(id: string, stroke: PaintStrokeInput): Promise<unknown> | void; undo(id: string): Promise<unknown> | void; clear(id: string): Promise<unknown> | void; end(id: string): Promise<unknown> | void; };
export function PaintEditor({ sessionId, paintApi, snapshot, previews = [], currentUserId, matrixClient, onSave }: { sessionId: string; paintApi: Api; snapshot: PaintSessionSnapshot; previews?: PaintPreview[]; currentUserId: number; matrixClient?: MatrixMediaClient; onSave?: (png: Blob) => Promise<void> }) {
  const sourceRef = useRef<HTMLCanvasElement>(null); const annotationRef = useRef<HTMLCanvasElement>(null); const imageRef = useRef<HTMLImageElement | null>(null); const points = useRef<PaintStrokeInput['points']>([]); const drawingRef = useRef({ strokes: snapshot.strokes, previews }); const [tool, setTool] = useState<PaintTool>('pen'); const [color, setColor] = useState('#161616'); const [width, setWidth] = useState(7); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState<string | null>(null); const host = snapshot.hostUserId === currentUserId;
  drawingRef.current = { strokes: snapshot.strokes, previews };
  const redraw = () => { const canvas = annotationRef.current; if (!canvas) return; const ctx = canvas.getContext('2d'); ctx?.clearRect(0, 0, canvas.width, canvas.height); [...drawingRef.current.strokes, ...drawingRef.current.previews].forEach(stroke => ctx && applyPaintStrokeToContext(ctx, canvas.width, canvas.height, stroke)); };
  useEffect(() => { if (!snapshot.source || !matrixClient || !sourceRef.current || !annotationRef.current) return; void loadPaintSourceImage(matrixClient, snapshot.source).then(image => { imageRef.current = image; initializePaintCanvases(sourceRef.current!, annotationRef.current!, image); redraw(); }).catch(reason => setError(reason instanceof Error ? reason.message : 'Unable to load source image.')); }, [matrixClient, snapshot.source]);
  useEffect(() => { redraw(); }, [snapshot.strokes, previews]);
  const input = (): PaintStrokeInput => ({ correlationId: crypto.randomUUID(), generation: snapshot.generation, tool, ...(tool === 'pen' ? { color } : {}), width, points: points.current });
  const down = (event: React.PointerEvent<HTMLCanvasElement>) => { event.currentTarget.setPointerCapture?.(event.pointerId); points.current = [normalizeCanvasPoint(event.clientX, event.clientY, event.currentTarget.getBoundingClientRect())]; };
  const move = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!points.current.length) return; points.current = [...points.current, normalizeCanvasPoint(event.clientX, event.clientY, event.currentTarget.getBoundingClientRect())]; void paintApi.sendPreview(sessionId, input()); };
  const up = () => { if (!points.current.length) return; void paintApi.commitStroke(sessionId, input()); points.current = []; };
  const save = async () => { if (!onSave || !imageRef.current) return; setSaving(true); setError(null); try { await onSave(await composePaintPng(imageRef.current, imageRef.current.naturalWidth, imageRef.current.naturalHeight, snapshot.strokes)); setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save to chat. Please try again.'); } finally { setSaving(false); } };
  return <section className="paint-editor"><PaintToolbar tool={tool} color={color} width={width} onTool={setTool} onColor={setColor} onWidth={setWidth} /><div className="paint-canvas-stack"><canvas ref={sourceRef} data-testid="paint-source-canvas" /><canvas ref={annotationRef} data-testid="paint-annotation-canvas" onPointerDown={down} onPointerMove={move} onPointerUp={up} /></div>{error && <p role="alert">{error}</p>}<div className="paint-actions"><button onClick={() => void paintApi.undo(sessionId)}>Undo</button>{host && <><button onClick={() => void paintApi.clear(sessionId)}>Clear</button><button onClick={() => void paintApi.end(sessionId)}>End</button><button onClick={() => void save()} disabled={saving || saved}>{saved ? 'Saved to chat' : saving ? 'Saving...' : 'Save to chat'}</button></>}</div></section>;
}
